// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using smarttournamentengine.STE.infrastructure;

#nullable disable

namespace _.ste.infrastructure.migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20260505061448_InitialCreate_2")]
    partial class InitialCreate_2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("smarttournamentengine.STE.Entity.Alphabet", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Alphabets");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Value = "A"
                        },
                        new
                        {
                            ID = 2,
                            Value = "B"
                        },
                        new
                        {
                            ID = 3,
                            Value = "C"
                        },
                        new
                        {
                            ID = 4,
                            Value = "E"
                        },
                        new
                        {
                            ID = 5,
                            Value = "F"
                        },
                        new
                        {
                            ID = 6,
                            Value = "G"
                        },
                        new
                        {
                            ID = 7,
                            Value = "H"
                        },
                        new
                        {
                            ID = 8,
                            Value = "I"
                        },
                        new
                        {
                            ID = 9,
                            Value = "J"
                        });
                });

            modelBuilder.Entity("smarttournamentengine.STE.Entity.Group", b =>
                {
                    b.Property<string>("GroupID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TournamentID")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("GroupID");

                    b.HasIndex("TournamentID");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("smarttournamentengine.STE.Entity.Match", b =>
                {
                    b.Property<string>("MatchID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AwayScore")
                        .HasColumnType("int");

                    b.Property<string>("AwayTeam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HomeScore")
                        .HasColumnType("int");

                    b.Property<string>("HomeTeam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MatchID");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("smarttournamentengine.STE.Entity.Team", b =>
                {
                    b.Property<string>("TeamID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("GroupID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TournamentID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("TournamentMode")
                        .HasColumnType("int");

                    b.HasKey("TeamID");

                    b.HasIndex("GroupID");

                    b.HasIndex("TournamentID");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("smarttournamentengine.STE.Entity.TeamGroupID", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("GroupID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeamID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("TeamGroupIDs");
                });

            modelBuilder.Entity("smarttournamentengine.STE.Entity.User", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Role")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("smarttournamentengine.Tournament", b =>
                {
                    b.Property<string>("TournamentID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TournamentID");

                    b.ToTable("Tournaments");
                });

            modelBuilder.Entity("smarttournamentengine.STE.Entity.Group", b =>
                {
                    b.HasOne("smarttournamentengine.Tournament", null)
                        .WithMany("Groups")
                        .HasForeignKey("TournamentID");
                });

            modelBuilder.Entity("smarttournamentengine.STE.Entity.Team", b =>
                {
                    b.HasOne("smarttournamentengine.STE.Entity.Group", null)
                        .WithMany("Teams")
                        .HasForeignKey("GroupID");

                    b.HasOne("smarttournamentengine.Tournament", null)
                        .WithMany("Participants")
                        .HasForeignKey("TournamentID");
                });

            modelBuilder.Entity("smarttournamentengine.STE.Entity.Group", b =>
                {
                    b.Navigation("Teams");
                });

            modelBuilder.Entity("smarttournamentengine.Tournament", b =>
                {
                    b.Navigation("Groups");

                    b.Navigation("Participants");
                });
#pragma warning restore 612, 618
        }
    }
}
